name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        run: |
          docker buildx build . --push \
            --cache-from ghcr.io/niklasrosenstein/hcloud-usage-exporter:cache \
            --cache-to ghcr.io/niklasrosenstein/hcloud-usage-exporter:cache \
            -t ghcr.io/niklasrosenstein/hcloud-usage-exporter:latest
