name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: niklasrosenstein/hcloud-usage-exporter

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        run: |
          docker buildx build . --push \
            --cache-from ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache \
            --cache-to ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
