name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: niklasrosenstein/hcloud-usage-exporter

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install pdm && pdm install
      - name: Ruff check
        run: pdm run ruff check
      - name: Ruff format check
        run: pdm run ruff format --check --diff

  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        run: |
          docker buildx build . --push \
            --cache-from ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache \
            --cache-to ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
